### ISSUE TITLE
XML example code on guidelines, code lines too wide

### ISSUE THREAD

**Issue by emunozh** [cstb/citygml-energy#100]
Many code lines on XML example code on guidelines are too wide for the rendered [pdf](https://github.com/emunozh/citygml-energy/blob/master/doc/guidelines/Guidelines_EnergyADE.pdf)

Here is a list of the lines with problems (cd: code line, pdf: page number on the pdf file):

- [ ] cd:   92:138  - pdf: p.8  gioagu@ea5eaf ; RomainNouvel@18697cd
- [ ] cd:  204:217  - pdf: p.11 JoachimBenner@6471fc5
- [ ] cd:  219:236  - pdf: p.11 JoachimBenner@6471fc5
- [ ] cd:  238:250  - pdf: p.11 JoachimBenner@6471fc5
- [ ] cd:  272:306  - pdf: p.12 gioagu@b123393
- [ ] cd:  337:358  - pdf: p.14 gioagu@3bee121
- [ ] cd:  399:435  - pdf: p.15 gioagu@03aa537; RomainNouvel@ae20fd2
- [ ] cd:  438:471  - pdf: p.16 gioagu@03aa537
- [ ] cd:  521:542  - pdf: p.19 RomainNouvel@d777ed2 ; gioagu@03aa537
- [ ] cd:  544:565  - pdf: p.19 RomainNouvel@d777ed2 ; gioagu@03aa537
- [ ] cd:  624:644  - pdf: p.22 gioagu@1275498 ; gioagu@3bee121 ; gioagu@f873542
- [ ] cd:  646:658  - pdf: p.22 gioagu@1275498 ; gioagu@3bee121 ; gioagu@f873542
- [ ] cd:  660:677  - pdf: p.23 gioagu@1275498 ; gioagu@3bee121 ; gioagu@f873542
- [ ] cd:  730:751  - pdf: p.25 gioagu@3bee121 ; gioagu@74738ef ; gioagu@f873542
- [ ] cd:  753:791  - pdf: p.25 gioagu@3bee121 ; gioagu@74738ef ; gioagu@f873542
- [ ] cd:  797:811  - pdf: p.26 gioagu@3bee121 ; gioagu@74738ef
- [ ] cd:  907:915  - pdf: p.31 gioagu@1275498
- [ ] cd:  938:987  - pdf: p.31 JoachimBenner@6471fc5
- [ ] cd: 1034:1089 - pdf: p.35 gioagu@03aa537; gioagu@3bee121
- [ ] cd: 1140:1176 - pdf: p.38 gioagu@1275498
- [ ] cd: 1206:1230 - pdf: p.39 gioagu@1275498 ; gioagu@64edc87

**Comment by JoachimBenner** [comment]
Central problem is that all nested XML tags are in indented by **4** spaces. With authering tools like Oxygen this can easily be changed to an indentation of for instance **1** space. Shall I do this for the complete guidelines file?

Oxygen can also make an automatic wrapping of long lines. Estaban, what is your proposal of a maximal line (in number of characters)?

**Comment by RomainNouvel** [comment]
Reducing the indent to 1 space wouldn't solve most of these cases and would damage the code readibility (I would suggest 2 spaces at less...).
1- in the pdf, the code font looks very big (even if it is the same than the body text). Could it be possible to reduce the font of XML examples, relatively to the body text?
2- Some of the comments are a way too long, we have to shorten them

**Comment by emunozh** [comment]
+1 for 2 spaces

I will modify the latex template to reduce the font size of all XML examples

**Comment by emunozh** [comment]
New XML code style on guidelines: 

![listing](https://cloud.githubusercontent.com/assets/1773370/14366467/2123ce7c-fd13-11e5-9bcc-ecfadee71978.png)

The document is now using the [Listings Package](http://www.texdoc.net/texmf-dist/doc/latex/listings/listings.pdf). I add the option `breaklines` to the Latex template. This is a quick fix to this issue. Please have a look at the updated [pdf](https://github.com/emunozh/citygml-energy/blob/master/doc/guidelines/Guidelines_EnergyADE.pdf) file.

**Comment by RomainNouvel** [comment]
Looks good. Can you try 1 Point font bigger and with only 2 indents instead of 4, to compare?
I'm not very fan of the shadow effect but why not :-).
Otherwise, could you introduce a new line after the paragraph titles Level 3?

**Comment by emunozh** [comment]
- Change the font size to '\footnotesize' and removed the shadow :+1:
- Add a space for Level 3 titles.

![codeexample2](https://cloud.githubusercontent.com/assets/1773370/14442039/fd22ba4c-0037-11e6-9a0d-70de2cc71b77.png)

**Comment by RomainNouvel** [comment]
Looks great! What happened to the table of content?
