### ISSUE TITLE
Line-wrapping on guidelines

### ISSUE THREAD

**Issue by emunozh** [cstb/citygml-energy#102]
Please use hard line-wrapping on guidelines markdown file. See http://www.cirosantilli.com/markdown-style-guide/#line-wrapping for a nice explanation on why should we use hard line-wrapping within a git repository.

**Comment by oliviertournaire** [comment]
@emunozh Are guidelines now consistent with you request?

**Comment by emunozh** [comment]
No, there are still many lines using a wrong line-wrapping. It is not a problem for the compilation of the document but it makes sense to track lines on a git repo rather than paragraphs. It is not helpful if I keep changing the wrapping because I destroy the commit history (it is harder to track changes). This is a matter of style. If having hard line-wrapping is to difficult for the group we should change to soft wrapping. Now we have a mix of both...

I'm fine either way and would be happy to change the file to either hard of soft wrapping.

**Comment by RomainNouvel** [comment]
According with the document history, this problem comes only from the update of @mlauster from the 14th of April. @mlauster, could you set your text editor in the way decribed by @emunozh, so that we all use the same text format (hard line-wrapping), and update your module Energy Systems with the new format? Regards

**Comment by mlauster** [comment]
I'm using github's online editor, I don't think that this one isn't capable of hard line wrapping. However, I shortened all lines (except one all not in my part of the Guidelines) and will have an eye on what my commits are doing.
