### ISSUE TITLE
Cardinality of relation "energyDistribution"

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#108]
In the version 0.6 of the Energy ADE, an EnergyDemand may have several EnergyDistributionSystem, because of the cardinality 0..* of the relation "energyDistribution". Is that possible? Will that be useful / useable in urban energy modelling?

I will suggest to fix a maximum of 1 EnergyDistributionSystem per EnergyDemand -> Cardinality of relation energyDistribution : 0..1.

**Comment by mlauster** [comment]
I agree. Any other comments?

**Comment by RomainNouvel** [comment]
Request of Change:
- Cardinality of relation energyDistribution (between EnergyDistributionSystem and EnergyDemand) : 0..1 instead of 0..*

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
