### ISSUE TITLE
Integrate Parameters for LCA - phase construction/refurbishment

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#110]
Up to know, we've only considered the primary energy and CO2 emissions for the operational phase of the building. More and more urban analyses consider also the "grey energy" and the "embodied carbon" to take some decision.

Here is a proposal discussed with Alessio, to integrate (step by step) the construction/refurbishment phase in our Energy ADE:

In the Construction Module:
- introduction of the new attribute EmbodiedCarbon in the class "SolidMaterial" : optional, measureType (generally kgCO2/m3 or kgCO2/kg), definition : CO2 equivalent emissions caused by the fabrication and transportation on site of the material.
- introduction of the new attribute EmbodiedEnergy in the class "SolidMaterial" : optional, measureType (generally J/m3 or J/kg), definition : Primary energy consumed for the fabrication and transportation on site of the material.
- introduction of the new attribute LifeSpan in the class "Construction" : optional, TimePeriod type (or Time length), definition: Period of service life, including the construction/installation date and the expected end of life.
- introduction of the new attribute LifeSpan in the class "Layer" : optional, TimePeriod type (or Time length), definition: Period of service life, including the construction/installation date and the expected end of life.

In the Energy and System Module:
- introduction of the new attribute LifeSpan in the class "EnergyConversionSystem", "EnergyDistributionSystem" and "_StorageSystem" : optional, TimePeriod type (or Time length), definition: Period of service life, including the construction/installation date and the expected end of life.

**Comment by RomainNouvel** [comment]
Sometimes, the life expectancy is known, but not the precise start of life. In this case, the TimePeriod attribute LifeSpan won't be adapted.
Instead of it, we could have an object ServiceLife with two optional attributes: startOfLife (Date) and lifeExpectancy (TimeLength), and also possibly mainMaintenanceInterval (TimeLength)

**Comment by mlauster** [comment]
I'm fine with @RomainNouvel proposal. Any other comments?

**Comment by RomainNouvel** [comment]
Reformulation of the Request of Change:

General (Energy ADE Core?) :

- Creation of a new object called ServiceLife, with three optional attributes: startOfLife (Type : DateType, Definition : Date where a product has been put into service for the first time (e.g. installation, construction)), lifeExpectancy (Type: TimeLength, Definition : Length of the service life of a product which is expected at its installation or construction), and  mainMaintenanceInterval (Type: TimeLength, Definition : Average period of time between two consecutive main maintenance operations)

In the Construction Module:

- introduction of the new attribute EmbodiedCarbon in the class "SolidMaterial" : optional, measureType (generally kgCO2/m3 or kgCO2/kg), definition : CO2 equivalent emissions caused by the fabrication and transportation on site of the material.
- introduction of the new attribute EmbodiedEnergy in the class "SolidMaterial" : optional, measureType (generally J/m3 or J/kg), definition : Primary energy consumed for the fabrication and transportation on site of the material.
- introduction of the new attribute ServiceLife in the class "Construction"
- introduction of the new attribute ServiceLife in the class "Layer"

In the Energy and System Module:
-  introduction of the new attribute ServiceLife in the class "EnergyConversionSystem", "EnergyDistributionSystem" and "_StorageSystem".

**Comment by oliviertournaire** [comment]
The ServiceLife attribute has been added in the class `LayerComponent` and not in the class `Layer`. Is it intended? If yes, issue can be closed (all other requests have been implemented)
@RomainNouvel @JoachimBenner

**Comment by JoachimBenner** [comment]
Yes from me
