### ISSUE TITLE
Missing EnergyCarrierTypeValues value for geothermal energy

### ISSUE THREAD

**Issue by mlauster** [cstb/citygml-energy#111]
For heat pumps, it is necessary to have geothermal energy as EnergyCarrierTypeValue. I propose to add `GeothemalEnergy`

**Comment by RomainNouvel** [comment]
Actually, this depends on the EnergyCarrier definition. Our actual definition is quite vague: "Energy form containing the energy (e.g. fuel, renewable energy etc.)". The distinction between "Energy Carriers" and "Primary Energy Sources" is extremely important. For instance, non-extracted gas in the Siberian ground is a Primary Energy Source, while gas in the gas network of the Aachen Stadtwerke is a Energy carrier.
For the same reason, I would consider geothermal energy rather like a primary energy source than an Energy carrier. For the same reason, I would drop down the "solar energy" from the EnergyCarrierTypeValue" code list.

I would also explicit the definition of the EnergyCarrier object : "Energy form containing the energy, occuping intermediate steps in the energy-supply chain between primary sources and end-use applications".

to be discussed of course...

**Comment by RomainNouvel** [comment]
Concerning Heat Pumps, the Energy Carrier would be only electricity for me...

Here is an interesting link: https://www.ipcc.ch/publications_and_data/ar4/wg3/en/ch4s4-3-4.html

**Comment by mlauster** [comment]
Hm, but then the structure of EnergySource and EnergyCarrier is not coherent. We define an EnergySource that has an energyAmount and an EnergyCarrier. What is an EnergyCarrier in context of an EnergySource? For a coal plant, this would be the coal, for a heat pump, this would be geothermal energy and electricity. And then we assign co2EmissionFactor and PrimaryEnergyFactor to this EnergyCarrier, what makes only sense if we deal with some kind of primary energy source or carrier. So from my perspective, we are talking about primary energy sources and we might specify the energy carrier of our system in the EnergyDemand. But of course, it's not easy to distinguish between primary energy sources and energy carriers in our context. E.g. for a DistrictNetworkSubstation, the EnergyCarrier (or EnergySource) it consumes is hot water, what is a carrier, the associated primary energy source depends on the plant that produces the hot water. So in some cases we reflect the entire energy supply chain (e.g. heat pump) and in some we would like to cut-off in between (e.g. DistrictNetworkSusbstation). But for both cases, we want to be able to define Carrier and PrimaryEnergySource and clearly distinguish between them.
Quite not easy to solve, I think this is why we have that mixture of Carriers and Sources in EnergyCarrierTypeValues. The easiest solution would be to keep this mixture and add GeothermalEnergy. ;-)

**Comment by RomainNouvel** [comment]
EnergySource is actually a fuzzy name, leading to confusions. Let's call it "FinalEnergy" to be clearer, whose definition is known by everybody.

**Comment by RomainNouvel** [comment]
Request of Change:
- Rename EnergySource -> FinalEnergy (Definition : Energy form containing the energy, occuping intermediate steps in the energy-supply chain between primary energy sources and end-use demands)
- Remove "solar energy" from the EnergyCarrierTypeValue" code list.

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
