### ISSUE TITLE
Delete relations isConsumedBy and isProcudecBy

### ISSUE THREAD

**Issue by mlauster** [cstb/citygml-energy#112]
Purpose is to link from `EnergySource` to `EnergyConversionSystem`, but is there a real use case where somebody uses this way instead of linking from an `EnergyConversionSystem` to an `EnergySource` using `consumes` and `produces`?
If not, I vote for deleting them.

**Comment by RomainNouvel** [comment]
The use of the different relations must be demonstrated with new examples...

**Comment by JoachimBenner** [comment]
@mlauster, @RomainNouvel can we come to a decision with this issue?

**Comment by mlauster** [comment]
We have still no use case for it, so I still vote for remaining it.

**Comment by RomainNouvel** [comment]
:+1:

**Comment by JoachimBenner** [comment]
O. k., let's decide to remove the relations

**Comment by RomainNouvel** [comment]
@JoachimBenner : Morith and I voted to **keep** the relations, not removing them :-)

**Comment by JoachimBenner** [comment]
Sorry, I am a little bit confused because Moritz at the beginning voted for "deleting", and then for "remaining". @mlauster can you clarify this?

**Comment by mlauster** [comment]
Oh, sorry, I meant removing. But if @RomainNouvel would like to keep them, I'm also fine with it.

**Comment by RomainNouvel** [comment]
Since we can't come to an agreement without having tested it, Let's leave it as it is, and test it in the next months...
