### ISSUE TITLE
New efficiency related attributes in HeatPump and CombinedHeatAndPower

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#113]
Request of Change: (coming from WG conf call discussion):
1- in object HeatPump : 
- Delete carnotEfficiency
- Add the optional attributes "copSourceTemperature" (Type: MeasureType, Definition: Source temperature defining the Coefficient Of Performance of the heat pump) and "copOperationTemperature" (Type: MeasureType, Definition: Operation or supply water temperature defining the Coefficient Of Performance of the heat pump)

2- in object ConbinedHeatPower:
- Add the optional attributes "thermalEfficiency" (Type: ScaleType, Definition : Efficiency of the heat production, corresponding to the quotient of the thermal output over the fuel input) and "electricalEfficiency" (Type: ScaleType, Definition : Efficiency of the power production, corresponding to the quotient of the electrical output over the fuel input)

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
