### ISSUE TITLE
Use of CodeLists in Occupancy Module

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#115]
The codelists OccupantType, OwnershipType, ResidenceType, HouseholdType may have some standardized equivalent in the INSPIRE directive. It would be interesting to reuse these standardised values, if adapted.
OccupantType : http://hub.geosmartcity.eu/registry/codelist/OccupantTypeValue/
OwnershipType : http://hub.geosmartcity.eu/registry/codelist/OwnershipTypeValue/

ResidenceType and HouseholdType could be later added in the registry

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
