### ISSUE TITLE
How to specify U-values at building scale?

### ISSUE THREAD

**Issue by oliviertournaire** [cstb/citygml-energy#119]
I am wondering how it is possible to define U values at building scale only. Let's say that a building is modeled in LOD 0 (lod0Footprint + measuredHeight) or in LOD 1, it can be interesting for some simulation tools to define a single U value for the walls and / or the ground and / or the roof.

I can use several `Construction` instances and attach them to the building, but how can I differentiate them (except using a convention that fills the `gml:name` or `gml:description`)?

**Comment by JoachimBenner** [comment]
With the 0.7.0 model, _Construction_ instances can only be attached to  _ _BoundarySurface_, _ _Opening_ or _ThermalComponent_. Thus, it is **not possible** to define a list of "Building-Constructions", and as Olivier said it is not possible to differentiate a _Construction_ instance as "Facade-Construction" or "Roof-Construction". If this is a real issue, we must define a specific ADE-property of _ _AbstractBuilding_.

**Comment by oliviertournaire** [comment]
I suggest to reopen the issue and discuss about it!

**Comment by JoachimBenner** [comment]
Yes, I agree with you, but for 0.7.0 we should stay with the actual solution. I am sorry, but I need to finish the work on version 0.7.0 with this week.

**Comment by oliviertournaire** [comment]
Yes, no problem. I set the milestone to _backlog_ so that we can discuss it later.

**Comment by gioagu** [comment]
I would like to widen a little bit the discussion and say that, actually, the original idea of having every single CityObject be linked to a Construction was not that bad, as this actually makes sense in the real (constructed) world!
What is more, I believe the construction module would fit very well also outside the Energy ADE (e.g. UtilityNetwork ADE?) with minor additions/changes, so I believe it is time to start thinking how to proficiently "recycle" the module also in other contexts.

So, I would like to (re)open the discussion, here or maybe during the next workshop.

Just like the Occupancy module can be used well beyond energy applications, why not also the construction and materials one?

**Comment by RomainNouvel** [comment]
Hi,
The fact that the object Constructions (and its related module) appears as attribute twice in the Energy ADE (ThermalComponent and BoundarySurface... and maybe ThermalBoundary) doesn't mean that we can't reuse/recycle it in other ADEs. Exactly like the objects Occupants or Household.
Or did I misunderstood your comment Giorgio?

**Comment by JoachimBenner** [comment]
Change Request: Introduction of an ADE attribute buildingMainConstruction

**Comment by JoachimBenner** [comment]
Can we agree on this change for version 0.9.0?

**Comment by RomainNouvel** [comment]
Ok, how can we define it? Equivalent construction of the building? Construction of most building surface?

**Comment by gioagu** [comment]
Ok for the concept, regarding the name, my proposal:

...BuildingConstruction

with ... being something like:

- equivalent
- (most)characterstic
- aggregated
- something else?
