### ISSUE TITLE
3DCityDB Extension for Energy-ADE

### ISSUE THREAD

**Issue by yaozhihang** [cstb/citygml-energy#121]
Dear Energy-Team,

this Github-repository (see the link below) might be useful for some of you who have an interest in using the open source software 3DCityDB for managing CityGML-Energy-ADE data. I would be glad about any feedbacks from you for improving my work. 

https://github.com/yaozhihang/3DCityDB-Extensions-for-CityGML-ADEs

Kind regards,

Zhihang

**Comment by pgcipriano** [comment]
Indeed, it would be very useful and interesting to discuss about different database implementations during the next Energy ADE workshop:
http://en.wiki.energy.sig3d.org/index.php/Workshop_Ferrara_2016

@yaozhihang ... are you coming?

**Comment by yaozhihang** [comment]
@pgcipriano I will not be attending this workshop and my colleague Mostafa ElFouly will be there. But, i'll be happy to give a short presentation about my work via Skype or GoToMeeting if possible.

**Comment by pgcipriano** [comment]
@yaozhihang thanks ... maybe we can schedule a short presentation of your work on Friday 25 in the morning, via skype. On Monday 7th we will discuss the final agenda with @RomainNouvel and other wg leaders.

**Comment by yaozhihang** [comment]
@pgcipriano Many thanks for giving the opportunity. I'll be looking forward to the final agenda of the workshop.
