### ISSUE TITLE
Industrial FeatureTypes in EnergyConversionSystem 

### ISSUE THREAD

**Issue by kwakuwulf** [cstb/citygml-energy#122]
_As discussed in Vienna I'm adding some issues from the viewpoint of industrial process modelling:_

Adding _chiller_ and _air compressor_ as feature types in `EnergyConversionSystem`.

**Comment by RomainNouvel** [comment]
Could you detail the required attributes of these two Systems @kwakuwulf ?

**Comment by kwakuwulf** [comment]
Chiller:
- `condensationType` (String)
- `compressorType` (String)
- `refrigerant `(String)
assuming required temperature is given elsewhere (issue open) and COP is defined as `nomincal efficiency`

AirCompressor
- `compressorType` (String)
- `pressure` (Decimal)

**Comment by RomainNouvel** [comment]
Can some of the string types be defined as codelist or enumeration, in order to make it easier to use?

**Comment by mlauster** [comment]
@kwakuwulf, could you define which attributes could be codelists or enumerations and what for values should be in this lists?

**Comment by kwakuwulf** [comment]
`compressorType` (chiller)
- Reciprocating compressor (hermetic)
- Reciprocating compressor (semi-hermetic)
- Reciprocating compressor (open)
- Rotary vane compressor
- Scroll compressor
- Screw compressor
- Centrifugal compressor

**Comment by kwakuwulf** [comment]
'condensationType'
- dry cooling
- evaporative cooling
- hybrid cooling
- adiabatic cooling
- free cooling

**Comment by kwakuwulf** [comment]
Actually, air compressors should have the same list as chiller-compressors (even tough maybe not all apply)

`refrigerants`: a bit tricky to set up a limited enumeration list since some producers constantly come up with new refrigerants so I would avoid that by leaving it open for any String

**Comment by mlauster** [comment]
@RomainNouvel, something to add here or this fine from your side?

**Comment by JoachimBenner** [comment]
This issue has been solved with version 0.8.0 and can be closed.
