### ISSUE TITLE
Heat Recovery in EnergySystem

### ISSUE THREAD

**Issue by kwakuwulf** [cstb/citygml-energy#125]
_As discussed in Vienna I'm adding some issues from the viewpoint of industrial process modelling:_

We've discussed internal heat recovery, which I would define in our context as follows: Using waste heat from within the company/building via heat exchanger or heat pump for an energy demand in the same company/building.

I can't right remember what the best way of defining internal heat recovery in the EnergyADE would be. We've discussed adding another `EnergyConversionSystem` named `(Waste)HeatExchanger` or even a generic EnergyConversionSystem.

 I leave this open for discussion.

**Comment by RomainNouvel** [comment]
Introducing a `HeatExchanger` (or `HeatExchangerStation`) as `EnergyConversionSystem` would be well adapted. Actually this is very close from the `DistrictNetworkSubstation` allready existing.
We could then have a general `HeatExchangerStation` object with a string attribute "primary heat supplier" which could be for instance "waste heat from company X" or "district heat from DHS Y" ...

**Comment by mlauster** [comment]
With such an `HeatExchanger` it should be possible to model internal heat recovery as well. Some `EnergyConversionUnit` would produce some `FinalEnergy` that can then be re-used by another `EnergyConversionSystem`, e.g. the `HeatExchanger`. For external use, the question is to define that the heat goes "out" of the building. One solution with the `HeatExchanger` is to define the heat it consumes and equally the heat it produces. The string gives the information to which node within the UtlilityNetwork ADE this heat then belongs to.

**Comment by kwakuwulf** [comment]
Would the `EnergyConversionUnit` (which produces `final energy`) then be linked to an `energydemand`? This would allow the mapping of waste heat potentials.
e.g. energy demand Z uses X amount of energy but also results in Y amount of waste heat

**Comment by RomainNouvel** [comment]
EnergyConversionUnit is not existing in the scheme Moritz, what do you mean with it? -> EnergyConversionSystem? If so, the answer to your question Wolfgang is yes!

**Comment by mlauster** [comment]
Sorry, I mean `EnergyConversionSystem`. I changed that

**Comment by mlauster** [comment]
Change of request:
Change feature type `DistrictNetworkSubstation` to `HeatExchanger` and add new string attribute `primaryHeatSupplier`

**Comment by mlauster** [comment]
Any objections? Otherwise I will add the label 'Validated by WG'.
