### ISSUE TITLE
GasStorageSystem

### ISSUE THREAD

**Issue by kwakuwulf** [cstb/citygml-energy#126]
_As discussed in Vienna I'm adding some issues from the viewpoint of industrial process modelling:_

Waste water treatment plants may even have `GasStorageSystems` from sludge treatment (biogas). 
Attributes: 
- `powerCapacity`
- `volume`
- `methan-content`

**Comment by kwakuwulf** [comment]
This may be rather something for the UtilityNetworkADE

**Comment by RomainNouvel** [comment]
The border between EnergyADE and UtilityNetworkADE is actually a long recurrent topic...
Our last agreement was that the border is approx. the "end of the garden". Then DistrictHeatSubstation may be integrated in the Energy ADE, but network and heating/power plants belongs to UtilityNetwork

**Comment by kwakuwulf** [comment]
I understand. I see it from the viewpoint of a WWTP (waste water treatment plant) which has energy demands like other industries and households and should thus be defineable in the EnergyADE. Gas production is a side product of the WWTP which can similarly be defined as waste energy (just in the form of biogas). So from this point of view the WWTP is rather a consumer with waste energy than a utility that has the main purpose of delivering energy to utility networks.

**Comment by mlauster** [comment]
This is still in discussion with UtilityNetworkADE and will be re-opened if the decision is to integrate it in Energy ADE
