### ISSUE TITLE
Occupancy Module: about class type of Facilities

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#132]
Hello!

This is, as a matter of fact, a direct continuation of the previous issue regarding the EnergySystem.
Piergiorgio and I were wondering whether it coule make sense to derive the class Facilities directly from _CityObject, similarly to the UsageZone and the BuildingUnit.

Or, on the other hand, why where they defined as Features (as they are now) and not as CityObjects?

What do you think?

g & pg

**Comment by gioagu** [comment]
Please refer to Issue 131 for the same reasons.

**Comment by JoachimBenner** [comment]
Proposal for version 0.9.0:

Derive the FeatureTypes _Facilities_, _Occupants_ and _Household_ from __CityObject_

**Comment by RomainNouvel** [comment]
ok

**Comment by gioagu** [comment]
hi,

actually, I agree for facilities being derived from _CityObject, but _not_ for Occupants and Households, as they refer (in my understanding) to people. See beginning of this ticket and link to ticket 131.

**Comment by JoachimBenner** [comment]
Can we agree on this change for version 0.9.0: 

The FeatureType _Facilities_ is derived from __CityObject_?

**Comment by gioagu** [comment]
yes, agree!
