### ISSUE TITLE
Change cardinality of relation ThermalOpening-->_Opening

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#133]
The current relation "relatesTo" has cardinality 0..1.

We should extend it to 0..* in order to be able to also define _ThermalOpenings (e.g. just in terms of global area in m^2) that actually correspond to (the sum of) multiple _Openings.

Agree?

**Comment by JoachimBenner** [comment]
I principally agree, but we must be careful. The restriction is that all these _Opening objects have the same orientation, which normally means that they belong to the same _BoundarySurface. This should be mentioned in the documentation.

**Comment by JoachimBenner** [comment]
Can we agree on this proposal

**Comment by RomainNouvel** [comment]
ok

**Comment by gioagu** [comment]
ok
