### ISSUE TITLE
Solar thermal parameters

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#134]
To be more comprehensible, we could replace the attribute names of SolarThermalSystem and PhotovoltaicThermalSystem:
eta0 -> zero heat loss efficiency (scaletype[0.1]), also called optical efficiency
a1 -> linear heat loss coefficient (numerical)
a2 -> quadratic heat loss coefficient (numerical)

**Comment by mlauster** [comment]
@RomainNouvel, could you put that in a request of change? Than we can approve that.

**Comment by RomainNouvel** [comment]
Request of Change: Rename parameters of the class ThermalSolarSystem more explicitly:
- eta0 -> opticalEfficiency (scaletype[0.1]). Def: corresponds to the zero heat loss efficiency. Generally noted eta0.
- a1 -> linearHeatLossCoefficient (numerical). Def : Linear coefficient of the heat loss polynomial equation. Also noted a1.
- a2 -> quadraticHeatLossCoefficient (numerical). Def : Quadratic coefficient of the heat loss polynomial equation. Also noted a2.
