### ISSUE TITLE
New feature type / city object for aggregations of weather data

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#135]
Energy ADE version 0.8.0 defines a new type WeatherData, providing a time series of data for one meteorological or physical parameter. In order to sufficiently support energy related simulations, a new feature type / city object is needed, which (1) aggregates **all weather data time series** which shall be used by a specific simulation and (2) can be integrated into an Energy ADE model as city object. Attached a proposal for a corresponding feature type **WeatherStation**. Comments are welcome

![weatherstation](https://cloud.githubusercontent.com/assets/6430204/24095997/f00ebf82-0d5f-11e7-96a3-ee90ae13f69a.jpg)

**Comment by JoachimBenner** [comment]
Can we agree on this proposal

**Comment by RomainNouvel** [comment]
I would wait the general concept of Sensor / SensorData, to see if we can integrate this case into it (we may have the same issue for a comfort station inside an office)
