### ISSUE TITLE
New optional attribute thematicDescription in TimeValuesProperties

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#136]
The data type **TimeValueProperties** enables the specification of a number of meta data of the related time series. I miss a textual property for a thematic sedcription of the time series values (e.g. dry-bulb temperature, relative humidity, hourly energy demand, ...),  One purpose of the proposed property is to use it in the legend of a diagram visualizing the time series values.

It might be that the attribute **source** is provided for this role, but the definition is too vague.

**Comment by RomainNouvel** [comment]
The class _TimeSeries might have already an "id" and "Name" automatically inherited (if it is not the case, then we should change the type of _TimeSeries).
The Attribute "source" is a contextual Attribute, describing the data lineage (who measures/simulates it? When?...). We may explicit that in the documentation /Guideline.

**Comment by JoachimBenner** [comment]
The attribute I request is neither a name nor an id. In order to support interoperability - and this should be the central goal of our development - we must avoid to use unspecfied and vague concepts like gml:name. It is much better to provide attributes with a specific meaning like thematicDescription.
