### ISSUE TITLE
Wall interior to ThermalZone

### ISSUE THREAD

**Issue by LydiaTC** [cstb/citygml-energy#138]
The CSTB needs to be able to create walls (or slabs) interior to a thermal zone (but not boundaries). 
Previously, in v.0.7, we would connect a thermalZone to 0..* thermalComponents to do this.
This is no longer possible in v0.8. in which we can only connect to thermalBoundaries.

We would suggest creating a parent class thermalComponent, with a specialisation as thermalBoundaries, and containing the 0..* thermalOpenings.

**Comment by JoachimBenner** [comment]
Do I understand it correctly: In your simulation model you need to represent building elements which have only a thermal capacity, but no thermal resistance? Is it necessary to represent the complete geometry, or at least geometrical parameters, of these components? Are the "internal" components related with openings, or is this only relevant for the real thermal boundaries?

**Comment by RomainNouvel** [comment]
Hi,
coming back to this issue. Lydia, could you precise the purpose(s) of these interior thermal components not considered as boundaries? Is it to model the thermal capacity of a zone? Or to prepare a future multizone simulation?
In the first case, I would suggest to rather work on a more detailed concept of our existing "effectiveThermalCapacity", which could include every kind of thermal masses (interior walls, furniture, stoves...)

**Comment by LydiaTC** [comment]
Hi,
I guess it is a little bit of both : the idea would be to be able to have different 'zonings' of a same building, where one wall could be either considered as a boundary between two zones or as an interior element giving thermal capacity to a zone.
This still needs to be worked on inside CSTB to clarify the pipeline. This is why I will close the issue for now and come back to it later when we agree inside CSTB on our need and how to approach it.
Thank you.
