### ISSUE TITLE
Expand BuildingType Codelist

### ISSUE THREAD

**Issue by oliviertournaire** [cstb/citygml-energy#23]
[Reported by Piergiorgio Cipriano]

In general, an alignment  with INSPIRE codelists is suggested.

BuildingType: at the moment the codelist (BuildingType.xml) is only containing 3 possible values:
* SingleFamilyHouse
* MultiFamilyHouse
* ApartmentBlock

We suggest to expand the codelist with the following:
* SFH (Single Family House)
* MFH (Multi Family House)
* TH (Terraced House)
* AB (Apartment Block)
* HLB (Historical large building)
* HSB (Historical small building)
The latter are crucial to estimate energy needs in historical centres (e.g. Ferrara, in Sunshine project).

**Comment by oliviertournaire** [comment]
What about this issue?

**Comment by JoachimBenner** [comment]
The INSPIRE Codelist http://hub.geosmartcity.eu/registry/codelist/BuildingTypeValue/ only contains the 4 items "Appartment Block", "Multi Family House", "Single Family House" and "Terraced House". We need to decide on a specific extension for  the Energy ADE.

The usage of acronyms or not must be discussed in the more general context, see issue #75

**Comment by RomainNouvel** [comment]
Further values for this codelist will be later added, independantly of the Energy ADE release.
What would be the added value of acronyms in our case?

**Comment by lucagiovannini** [comment]
Dear All,

Speaking on behalf of Piergiorgio, we can remuve the two extra cathegories of HLB and HSB as we have reconcilied them with the original 4 TABULA types.

Regarding the acronyms I would not use them for this attribute, they are rather uninformative.

**Comment by oliviertournaire** [comment]
In version v0.7.0, _Terraced House_ and _Row House_ have been added. Can be considered as closed for this version, but can still be reopened for a later version if more values have to be added.

**Comment by RomainNouvel** [comment]
Terraced House and Row House refer to the same type of building (terraced house seems to be the british specific word for it).
Then, we do not need to have it both in the codelist.
regards

**Comment by oliviertournaire** [comment]
OK. @JoachimBenner can you make the modification in the UML model?

**Comment by JoachimBenner** [comment]
I deleted Row House

**Comment by oliviertournaire** [comment]
OK, thanks
