### ISSUE TITLE
building Physics Description / construction type

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#44]
Some information about the building contruction type could be useful,  for instance to assess the materials of a buildings (information about building type and year of construction is sometimes not enough).

A attribute called "buildingPhysicsDescription" or "constructionType" (the "constructionStyle" of the version 0.5 doesn't look like a reference name) should be precisely defined and maybe set as a hierarchical CodeList.

(Some information about building construction type: http://www.wikihow.com/Determine-a-Building%27s-Construction-Type)

**Comment by JoachimBenner** [comment]
constructionStyle -> constructionWeight (Enumeration)
Change Request

**Comment by oliviertournaire** [comment]
Implemented in the latest version of the UML model
