### ISSUE TITLE
Landmarked / Historical Buildings

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#45]
Different status of landmarked/historical buildings exist in Europe with different degrees of protection.
Therefore, a simple landmarked[Boolean] as attribute of _AbstractBuilding should be not enough.
PROPOSITION:
- Use the Hierarchical/multi-lingual CodeList Re3gistry as developed by JRC to manage the different certification labels and degrees.
- Rename this attribute (culturalHeritageStatus?)

**Comment by oliviertournaire** [comment]
So, should the issue be closed?
