### ISSUE TITLE
UML Diagrams in readme

### ISSUE THREAD

**Issue by mlauster** [cstb/citygml-energy#70]
The UML Diagrams are currently linked in readme.md (source: doc/UML_diagrams/) as well as in Guidelines_EnergyADE.md (source: guidelines/fig/), what in turn is linked in readme.md. I propose to keep them solely in Guidelines_EnergyADE.md, this will improve readability and we don't have two different versions of UML's.

**Comment by oliviertournaire** [comment]
Fixed by commit https://github.com/cstb/citygml-energy/commit/1f53a47c6adc9268c18b015a6cd4c3dd4e060281
