### ISSUE TITLE
Name/Rename of "landmarked" attribute in class building

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#73]
Some comments to consider for the 0.7 version

Giorgio: In class Building_ADE, given that it is boolean, we should rename the attribute to “isLandmark”, for consistence with other attributes (isSunExposed, etc.)

Romain: We’ve decided that heritage and landmark building information would be not mentioned in the Energy ADE (but a proposition will be made to the CityGML 3.0 working group). As a consequence, this attribute should be deleted from the Energy ADE 0.6.

Joachim: I suggest to leave this attribute and follow Giorgio’s proposition to rename it to “isLandmarked”. It is correct that this is a general CityGML issue, but I expect CityGML 3.0 not before late 2017, if any. In IFC, a building also has such an attribute, which shows that it might be relevant for some applications.

**Comment by JoachimBenner** [comment]
Rename: landmarked --> isLandmarked

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
