### ISSUE TITLE
Add attribute "EnergyPerformanceCertification" also in class BuildingUnit

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#76]
Some comments/thought collected so far for release 0.7

Giorgio: The attribute “EnergyPerformanceCertification” should be added to the “Building_Unit” class as well. You can have EPC for the whole building, or for just a single unit. I remember we talked briefly about this in Munich, but somehow it got lost (I forgot it too…).
 
Romain: That’s right. -> Issue for Energy ADE 0.7?
 Joachim: Should be a topic for Energy ADE version 0.7

**Comment by JoachimBenner** [comment]
Agreed

**Comment by RomainNouvel** [comment]
Request of Change:
- Add attribute “energyPerformanceCertification” (Type: EnergyPerformanceCertification, cardinality 0..*) to the object "BuildingUnit"

**Comment by JoachimBenner** [comment]
Has been done

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
