### ISSUE TITLE
Redefine the "volume" attribute in _AbstractBuilding and ThermalZone

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#77]
Some thought ideas for the next version 0.7

This is a sort of extension of the floorArea idea (issue  #47), but with regards to volume. Some ideas were collected also in Issue #55
Currently, we only have two attributes: grossVolume, and netVolume (which is only in ThermalZone).
In reality, we may define several types of volume, such as:
netVolume,
grossVolume,
heatedVolume,
cooledVolume,
ventilatedVolume, etc.

We might even go further, especially when we derive volume from heterogeneous models, such as
lod1Volume,
lod2Volume,
lod3Volume.

Finally, we may think that you can cross these two lists and have something like:
lod2NetVolume,
lod2GrossVolume,
lod2VentilatedVolume, etc.
(looks weird, but it's for understanding)

So, my idea is to reshape the volume attribute in a similar way to the floorArea.
The attribute could be like:

volume: Volume_new [0..n] 

<<DataType>> Volume_new having
volume: Volume
volumeType: VolumeType

<<CodeList>> VolumeType
lod2NetVolume,
lod2GrossVolume,
lod2VentilatedVolume,
(or something else, it is an example).

In anycase, I would keep the codelist (and no enumeration) so that we can play around at the beginning. What is more, there are here for sure some issues with the names (Volume), but somebody may help to avoid homonimous objects - here I am not the expert.
What is more, there could be some hints from other standards about naming...

What do you think?

**Comment by mlauster** [comment]
It is a good idea to have the same concept for the floor_area issue than for the volume issue. Otherwise it will just confuse the user if we solve similar issues with different approaches.

**Comment by RomainNouvel** [comment]
I would not confuse the **nature** of the volume (e.g. net volume, gross volume, heated volume) and its **acquisition method** (e.g. calculated from the LoD1, calculated from the LoD2, based on architect plans). Therefore, I would rather support your first list, Giorgio.
The day we will integrate metadata into the city model, we will be able to know with which method the volume has been calculated..

**Comment by JoachimBenner** [comment]
Changes:

- New CodeList **VolumeTypeValues** with entries _NetVolume_, _GrossVolume_ and _EnergyReferenceVolume_
- New DataType **VolumeType** with 2 mandatory attributes **type** (_VolumeTypeValues_) and value (_Volume_)
- Changes in **_AbstractMuilding** and **ThermalZone**:
 - Rename attribute **grossVolume** --> **volume**
 - Change type to **VolumeType**
 - Change cardinality to **0..***

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
