### ISSUE TITLE
Time series for weather / climate data

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#79]
Weater or climate data are important input data for energy simulations. In version 0.6.0 we can specify time series of global solar irradiance and daylight illumanance for Boundary Surfaces. But there are many more relevant meteorological parameters like temperature, wind speed, relative humidity, .... Most of them must be connected to the building as a whole, as this is not possible in the actual version of the Energy ADE.

Thus, I propose to add the property **climateData: _TimeSeries[0..*]** as ADE attribute of _AbstractBuilding

**Comment by RomainNouvel** [comment]
Hi Joachim,
the question of integrating Weather data in building / city models is old like the world...
Weather data are generally not integrated in Building Information Models for instance. Instead, BPS tools use external weather file (.epw or .tmy) as inputs to simulate the heating demand of a building.
However, in urban energy modelling, some local weather data are already the results of a simulation (e.g. globalSolarIrradiance on the different facade, air temperature if considering the Urban Heat effect etc.), and would deserve to be at less referenced in the city model (or even stored inside). Weather data may also be specified as metadata, for instance precising how the heating demand has been simulated...

Before to take any decision (maybe only during the next workshop), it would be interesting to have the opinion of many of you, as well as some CityGML 3.0 developers (this problem is not specific to the Energy ADE)

**Comment by JoachimBenner** [comment]
From my point of view, weather data are real "data", not "metadata". If an Energy ADE model shall be processed by different simulation systems, the used weather/climate data must be specified in the input data set, because these data strongly influence the simulation result. 

Whether the time series values are directly integrated into the XML document (class RegularTimeSeries or IrregularTimeSeries) or stored on an external data set is a secondary technical question. For the latter case, we already defined the classes RegulatTimeSeriesFile / IrregulatTimeSeriesFile, and we surely can define additional classes to support other file formats like *.epw or *.tmy.

**Comment by JoachimBenner** [comment]
Shall be discussed in a broader context. Make a propoal in version 0.7.0

**Comment by JoachimBenner** [comment]
Changes:

- New CodeList **MeteorologicalParameterValues**
- New Type **WeatherOrClimateData** with mandatory attributes **parameter** (_MeteorologicalParameterValues_) and **values** _(_TimeSeries_)
- New ADE attribute **weatherOrClimateData** of **_AbstractBuilding** with type **WeatherOrClimateData** and cardinality **0..***

**Comment by RomainNouvel** [comment]
Hi Joachim,
I wouldn't integrate these meteorological parameters directly in the building model (class _AbstractBuilding) but instead in a sensor object, which could be related to any _CityObject (temperature can be also measured for a given building surface, or even a given storey, for instance for skycrapers). Is such a Sensor object already existing in CityGML? We should discuss about this in Vienna...

**Comment by RomainNouvel** [comment]
Proposition of solution :
- Introduce a new object "ClimaticMeasures" / "MicroclimaticMeasures" which would optionally extend _CityObject features --> then temperatures could be attached to a building, or a boundarySurface, or even a simple position in a city model.
- its attribute would be your "MeteorologicalParameterValues" (AirTemperature, SurfaceTemperature, WindSpeed, SolarGlobalIrradiance, DaylightIlluminance), MeasureData (_TimeSeries), and an optional Position
- we would then resolve also our issue concerning the assignment of "GlobalSolarIrradiance" to _BoudarySurface and/or ThermalBoundary

**Comment by JoachimBenner** [comment]
Hi Romain,

I agree that it is beneficial to attach the new class to _CityObject, which allows us to eliminate a number of specific attributes in _BoundarySurface, ThermalBoundary, etc. It is a good idea to provide an extra (optional) attribute for the geometrical position of the measurement. Under these conditions, I would derive the new class from _CityObject, which means that it can also be instanciated independently from any other Building or BoundarySurface object.

My only concern is whether the name **ClimaticMeasures** or **MicroclimaticMesures**  is really appropriate, but this is a minor point and can be discussed and decided in Vienna.

Does everyone agree that I adapt the 0.7.0 schema as Romain proposed?

**Comment by RomainNouvel** [comment]
Hi Joachim,
Maybe there's already a modell for such weather data in CityGML actually (related with sensors). Let's discuss it with Thomas and Volker during the workshop.
Regards,
Romain

**Comment by RomainNouvel** [comment]
Following the presentation and discussion of the Workshop in Vienna, can we state on this issue? @JoachimBenner @gioagu  ?
Here a proposition recap:
- Introduction of an Object "WeatherData" which would optionally extend _CityObject features.
- its attribute would be a mandatory "WeatherDataType" (from Enumeration WeatherDataTypeValues = {AirTemperature, SurfaceTemperature, WindSpeed, SolarGlobalIrradiance, DirectBeamIrradiance, DaylightIlluminance}), mandatory values (_TimeSeries), and an optional Position.
- then, we can delete GlobalSolarIrradiance and DaylightIlluminance in _BoundarySurface and/or ThermalBoundary, as well as the new attribute specific to _AbstractBuilding

Concerning the name "WeatherData", it is still discussable. ClimateData doesn't look appropriate (see difference weather vs. climate : http://www.diffen.com/difference/Climate_vs_Weather ). However, can we call weather data an irradiance incoming on a given specific boundary surface in a urban environment? Or MicroClimateData. @jaykae26 : any suggestions?

**Comment by JoachimBenner** [comment]
I agree with this proposal.
Concerning the property name, I am principally open for alternatives, but I would prefer "WeatherData".

**Comment by oliviertournaire** [comment]
@JoachimBenner @RomainNouvel `WeatherData` is currently implemented as a `type`. What about 

> Introduction of an Object "WeatherData" which would optionally extend _CityObject features
?

**Comment by JoachimBenner** [comment]
It is just modelled in this way

**Comment by oliviertournaire** [comment]
OK, so we can consider that issue has been mplemented in latest version of the UML model!
