### ISSUE TITLE
EnergyCarrierTypeValues - need Fernwaerme

### ISSUE THREAD

**Issue by anetefr** [cstb/citygml-energy#81]
If in real data there is energy source fernwärme, there is no place where to properly map it in enumeration EnergyCarrierTypeValues. 
I image that fernwärma will appear quite often in data. It could be added to enumeration.
However, then mandatory nature of "co2EmssionFactor" and "primaryEnergyFactor" might arise problems then.

**Comment by RomainNouvel** [comment]
Dear German fellow,
Please note that the CityGML Energy ADE uses the english language :-)
Ein Fernwärmenetz enthält Warmwasser ("HotWater") oder Dampf ("Steam") als Energieträger. Both HotWater and Steam are already set in the EnergyCarrierTypeValues CodeList. Naturally, the co2EmissionFactor and primaryEnergyFactor will be specific to the considered District Heating System, generally given by the energy supplier ("Stadtwerk").

**Comment by anetefr** [comment]
Alles klar! Danke!

**Comment by mlauster** [comment]
Is clarified.
