### ISSUE TITLE
InternalGains / HeatDissipation

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#82]
In the Energy ADE 0.6, we have the parameters "internalGains" in the UsageZone class, and the parameters "heatDissipation" in the Occupants and Facilities classes. These parameters are related, internalGains beeing the sum of the different heatDissipation inside the usage zone. Without definition clarifications, they look redundant. Actually,  the aim of internalGains is to provide the average aggregated heat gains dissipated by occupants and facilities inside the usage zone, in the case that these ones are not known in detailed.

Proposition:
- We should therefore rename explicitly the "internalGains" in "averageInternalGains" (unit: W or W/m2)
and clarify the definitions of heatDissipation and averageInternalGains:
- heatDissipation -> Definition: heat energy dissipated by the occupants, respectively facilities, in "nominal conditions", it means when all occupants are present, respectively the facilities are fully operating. The constant totalValue of heatDissipation is weighted by the occupancyRate, respectively the operationSchedule, to obtain the heat dissipation temporal variation.
- averageInternalGains -> Definition: aggregated average heat energy dissipated by the occupants and facilities in a usage zone over the whole year.

**Comment by JoachimBenner** [comment]
Do I understand it correctly, the averageInternalGains may either be specified as total power (unit W), or as total power per square metre floor area (unit W/m2)? This can be distinguished by the uom-identifier, but I think it should be made clear in the documentation / guidelines.

In the case of internalGains due to occupants of facilities, shall it also be possible to specify W/m2?

**Comment by RomainNouvel** [comment]
in UsageZone: averageInternalGains can be specified presently in W or W/m2. A related problem is : which floor area type (netto, gross etc.) refers to this "/m2". We could maybe keep only "W" to avoid this definition problem.
For Occupants and Facilities (which are not space but heat sources), heatDissipation should be written in W.

**Comment by bahujean** [comment]
I m OK with these changes:
"internalGains" (UsageZone) --> "averageInternalGains"

I think for "averageInternalGains" of "heatDissipation", they should be mentioned in W. It will avoid misunderstanding.

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
