### ISSUE TITLE
Little BUG in Energy ADE 0.6 due to typo

### ISSUE THREAD

**Issue by gioagu** [cstb/citygml-energy#85]
In the relation between Occupants and Households, there is a typo (both in the xsd and in the UML diagram) which reads:

consiststOf

Please note the double "st", which is an involuntarily typo - but definitely hard to spot ;-)
I think this should be corrected in the 0.6 version, too.

**Comment by JoachimBenner** [comment]
This typing error already existed in version 0.5.0. It was very easy to correct it in the EA-model and the XLM-schema. Who can update the GitHub documents?

**Comment by mlauster** [comment]
For that, we need to correct the typo in:
https://github.com/cstb/citygml-energy/blob/master/doc/FeatureCatalogue/html/energy_Occupancy.html
https://github.com/cstb/citygml-energy/blob/master/doc/FeatureCatalogue/html/energy_Occupants.html
and update the graphics:
https://github.com/cstb/citygml-energy/blob/master/doc/FeatureCatalogue/png/energy_Energy-ADE_Occupancy%20%28simplified%29.png
https://github.com/cstb/citygml-energy/blob/master/doc/FeatureCatalogue/png/energy_Energy-ADE_Occupancy.png
https://github.com/cstb/citygml-energy/blob/master/doc/guidelines/fig/class_occupancy.png

Who did this the first time? Maybe he could take care of that again? @oliviertournaire, you are the last mentioned in the commits, did you create the graphics?

**Comment by JoachimBenner** [comment]
I don't think we should really edit html pages. I have installed the corrected schema, feature catalogue and UML diagrams file on the CityGML Wiki (http://www.citygmlwiki.org/index.php/CityGML_Energy_ADE). Only for the EA model I would not  allow an open access, and I will ask Olivier to load the coorected file on GitHum.

**Comment by JoachimBenner** [comment]
Well, let's discuss relation names. From my point of view, neither "consistOf" nor "consistsOf" is an appropriate name for the relation from "Occupants" to "Household". Easier understandable would be "liveIn" or "occupy". The latter name would be consistant with the "occupiedBy" relation from BuildingUnit / UsageZode to Occupants,

**Comment by RomainNouvel** [comment]
"liveIn" or "occupy" do not describe well the relation between Occupants and Household, which are both a group of person.
What about a relation "households" or "household" depending on the convention?

**Comment by RomainNouvel** [comment]
Request of Change:
- rename relation between Occupants and Household into "household" (instead of "conststsOf")

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
