### ISSUE TITLE
DailyPatternSchedule

### ISSUE THREAD

**Issue by jaykae26** [cstb/citygml-energy#90]
The daily pattern schedules can be defined according to:
- Detailed schedule composed of daily schedules associated to recurrent day types (weekday, weekend etc.).

But.. how do you specify WHEN these days happen during the year? Of course an easy answer can be formulated for Monday to Sunday, but what about a Holiday? It can be at different periods of the year depending on the country.

**Comment by JoachimBenner** [comment]
The usage of daily schedules surely is a simplification. We can define a schedule for a "typical Monday", but not for a "Monday in January". If the latter is needed, the type *TimeSeriesSchedule* must be used, which allows to specify specific values for every day, or even every hour of the year.

The same is valid for the extra schedule during holidays. We can perhaps define a small number of different "Holiday Types", e.g. SummerHoliday / WinterHoliday od Holiday1 / Holiday2, but this will surely not cover every special case.

**Comment by RomainNouvel** [comment]
I understand the issue of Jerome. Without making this DailyPatternSchedule too complex, we should add the possibility to define specific periods of the year (winter, summer, holidays). We should also make sure that it could easily relate to dailyschedule libraries (->limited number of daytypes).

Here is a proposition:
- We introduce between DailyPatternSchedule and DailySchedule an object "SeasonalPeriod" or "YearlyPeriod" of type TM_Period. DailyPatternSchedule is composed of 1..* "SeasonalPeriod" (in pratice, 1 to 3) which are composed of 1..* "DailySchedule". In this way, no need to create something specific for holidays. Furthermore, the first day of the year (monday? Tuesday?) is defined by the absolute time reference defining the start of the "SeasonalPeriod".
- As a consequence, we can reduce the Enum DayType to the days of the week, WeekDay, WeekEnd, DesignDay, TypicalDay (which correspond to all other days). No need to precise the season.

**Comment by JoachimBenner** [comment]
I do not know whether there is a real use case for this, but we can of course procees in this way. For the precise modelling, we must take into account two things

- Issue #67, stating that the ISO types TM_Period and TM_TimePosition in principle refer to a concrete year. In the DailyPatternSchedule, I think we address a "typical" year.

- There must be a schedule for every day of the year. Thus, there should be some kind of "default schedule".

**Comment by RomainNouvel** [comment]
@jaykae26 has for sure plenty of examples for it (Jerome, could you provide some?).
I completly agree your two remarks:
- Issue #67 : I talked last week with Kanischk from TU München who is leading the development group Dynamizer of CityGML 3.0. They're developing "atomic time series" without absolute time reference. I'm sure we can get inspired from them.
- You mean "default period"? Default dailySchedule is already the purpose of "TypicalDay". We could call this Period "RestOfTheYear" or "MainPeriodOfTheYear".

**Comment by JoachimBenner** [comment]
Change request will be written by Romain

**Comment by RomainNouvel** [comment]
Request of Change:
- Introduction of the new object "PeriodOfTheYear" of type TM_Period, between DailyPatternSchedule and DailySchedule. DailyPatternSchedule is composed of 1..* "PeriodOfTheYear" which are composed of 1..* "DailySchedule". 
- Simplify the element of the Enum DayType : WeekDay, WeekEnd, DesignDay, TypicalDay, and all the days of the week (monday, tuesday etc.). All other elements may be deleted

I let you know as soon as Kanishk and Thomas tell us the solution to consider typical year (should be possible also with this request of change).

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
