### ISSUE TITLE
_SolarEnergySystem

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#91]
In the Energy ADE 0.6:
1. the SolarEnergySystem present only the geometrical information "collectorSurface", "panelAzimuth" and "panelInclination", and not a given geometrical surface.
2. Furthermore, it is linked only to BoundarySurface with an optional double relations:
  a) The "installedOn" relation from SolarEnergySystem to BoundarySurface is the mostly used case, where we want to calculate the photovoltaic electricity production of a given PV system, in particular to cover the electrical demand. This relation should be mandatory.
  b) The "equippedWith" relation from BoundarySurface to SolarEnergySystem has been originally designed for Photovoltaic Potential study, where the SolarEnergySystem is a floating object not related to an EnergyDemand. This relation could be avoid if the SolarEnergySystem is related in a way with a Building (which is possible with the relation "has" from AbstractBuilding to EnergyConversionSystem. 
3. The case of tilted PV panels on flat roof is not considered in our Schema (here, the SolarEnergySystem MUST be laid on a Roof/facade)
4. The attribute _area_ of SolarEnergySystem should be detailed (aperture area, module area, gross area?).
5. The present schema does not allow to integrate Hybrid PVT panels

**Propositions for Energy ADE 0.7:**
* It should be possible to relate SolarEnergySystem with a (outer) BuildingInstallation instead of a _BoundarySurface
* An optional attribute _surfaceGeometry_ , type GM_MultiSurface[0..1], would be required in the case that the solar panels do not correspond 1-to-1 to the BoundarySurface
* the attribute panelAzimuth and panelInclination are not necessary/relevant, from the moment that a relation exist between SolarEnergySystem and BoundarySurface, respectively BuildingInstallation (or if the optional attribute _surfaceGeometry_ is indicated).
* the relation "equippedWith" from BoundarySurface to SolarEnergySystem could be deleted.
* the relation "installedOn" from SolarEnergySystem to BoundarySurface, respectively BuildingInstallation, should have the cardinality 0..1 (if a Solar installation covers really several BoundarySurface, then it should be divided in several SolarEnergySystem).
* The SolarEnergySystem should be distinguished between "PhotovoltaicSystem" (with only attributes _moduleArea_ and _cellMaterialType_, since installedNominalPower (=peak power) and nominalEfficiency (=performance ratio) are already the attributes of EnergyConversionSystem), "SolarThermalSystem" (with attributes _apertureArea_, _eta0_, _a1_, _a2_ and _technologyType_) and "PhotovoltaicThermalSystem" (with all attributes of the two latters).

**Comment by RomainNouvel** [comment]
* _technologyType (or rather _CollectorType) of SolarThermalSystem and PhotovoltaicThermalSystem is an enumeration: "FlatPlaneCollector", "EvacuatedTubeCollector".
* _cellMaterialType (or rather _cellType since cellmaterial = silicon often) of PhotovoltaicSystem and PhotovoltaicThermalSystem is an enumeration:"Monocrystalline", "Polycrystalline", "Amorphous"...

**Comment by mlauster** [comment]
@jaykae26, can you comment on that and if @RomainNouvel made a good proposal, label this as ready for ADE Core?

**Comment by gioagu** [comment]
I am not so sure about adding a surfaceGeometry to the SolarEnergySystem. I understand and agree with the need, but I wonder whether it is the right approach.
As a matter of fact, any SolarEnergySystem (installed on a building) is per definition already an outer BuildingInstallation. Therefore, it is already possible to model it geometrically (though from LoD2).
As long as a SolarEnergySystem is a semantic object, ok, but so we may add a geometrical attribute to something that has already a geometry.

On the other hand: how would you model a solar panel that is not "mounted" on a building, e.g. like in solar power plant?
So I agree that simply extending a BuildingInstallation would not suffice or cover all the cases.

**Comment by JoachimBenner** [comment]
I mostly agree with the proposal of Romain. The only exception is the topic

> The relation "installedOn" from SolarEnergySystem to BoundarySurface, respectively BuildingInstallation, should have the cardinality 0..1 (if a Solar installation covers really several BoundarySurface, then it should be divided in several SolarEnergySystem).

In existing CityGML data, the division of e.g. a building wall or roof into WallSurface / RoofSurface objects is sometimes a little bit arbitrary. Thus, in some cases it might be difficult to divide a solar installation among different boundary surfaces. We should leave the cardinality 0..*, but add an (informal) restriction, that all referenced BoundarySurfaces must have the same orientation (azimuth and inclination).

We can make the _SolarEnergySystem attributes optional, but then we must clearly state that

- either a relation to a BuildingInstallation or to BoundarySurfaces must be available, and
- the solar installation covers the total area of the BuildingInstallation or BoundarySurfaces.

Because the latter condition may not always be fulfilled, I thik we need an extra geometry property surfaceGeometry of _SolarEnergySystem

**Comment by RomainNouvel** [comment]
The original (and, I think,  only) purpose of the relation "installedOn" is to get the solar irradiance (in W/m²) incoming on the BoundarySurface or BuildingInstallation on which the SolarEnergySystem is installed, in order to calculate ist Energy yield (based on the area of the solar System).
Then, in the case that a Roof is divided in several small BoundarySurface with the same orientation, the incoming solar irradiance of all of them will be identical (unless if there is a very close obstruction object). Then, no need to have a cardinality 0..* of "installedOn" in this case, just mentioning that the "SolarEnergySystem" is "installedOn" the mostly covered BoundarySurface.

**Comment by mlauster** [comment]
@RomainNouvel, @JoachimBenner, is there an agreement on this? DOes core takes care of implementation?

**Comment by RomainNouvel** [comment]
Request of Change [DRAFT]:
- new relation "installedOn" from _SolarEnergySystem to BuildingInstallation
- new optional attribute surfaceGeometry in _SolarEnergySystem, type GM_MultiSurface[0..1]
- delete attributes panelAzimuth and panelInclination in _SolarEnergySystem
- delete relation "equippedWith" from BoundarySurface to _SolarEnergySystem.
- new attributes moduleArea (AreaType) and cellType (enumeration) in PhotovoltaicSystem. The elements of cellType are "Monocrystalline", "Polycrystalline", "Amorphous". Delete cellMaterialType.
- new attributes apertureArea (AreaType), eta0 (double), a1 (double), a2 (double) and collectorType (enumeration) in SolarThermalSystem. The elements of collectorType are "FlatPlaneCollector", "EvacuatedTubeCollector". Delete technologyType. 
-  new class PhotovoltaicThermalSystem which inherits from _SolarEnergySystem (Definition : hybrid photovoltaic and solar thermal system), with the attributes of both PhotovoltaicSystem and SolarThermalSystem.

Still to be discussed:
- relation "installedOn" from _SolarEnergySystem to BoundarySurface, respectively BuildingInstallation, should have the cardinality 0..1 (if a Solar installation covers really several BoundarySurface, then it should be divided in several SolarEnergySystem).

**Comment by JoachimBenner** [comment]
I made the following additional changes:
- For consistancy reasons, the relation "installidIn" points from EnergyConversionSystem to _CityObject
- The attribute "collectorSurface" of _SolarEnergySystem is deleted, because it is replaced by the more specific attributes "apertureArea" / "moduleArea" in the derived classes.
- The two new enumeration properties (cellType / collectorType) are specified as mandatory attributes, all other new properties are optional. Is this o.k.?

**Comment by mlauster** [comment]
Sounds good for me. @RomainNouvel, do you have something to add?

**Comment by RomainNouvel** [comment]
Hi Joachim,
Ok for your reported changes. Do you plan to implement also the further requested changes of this issue in the new Energy ADE 0.7? Do you have some remarks about them?

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model.
@JoachimBenner Just a short comment: attributes _a1_, _a2_, _apertureArea_, _collectorType_ and _eta0_ can be moved to an abstract class. Thus, SolarThermalSystem and _PhotovoltaicThermalSystem_ would inherit this class (just a refactoring issue). Issue cand be reopened later based on this comment
