### ISSUE TITLE
Double Relation EnergyConversionSystem <-> _AbstractBuilding

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#92]
in the version Energy ADE 0.6: 2 relations exist to link EnergyConversionSystem and _AbstractBuilding:
1- "has" goes from _AbstractBuilding to EnergyConversionSystem.
2- 'installedIn" goes from _EnergyConversionSystem

This loop isn't very pretty/practical for modellers

I wonder why the second relation is useful. Couldn't we delete "installedIn"?
"has" is a pretty general term. Couldn't we use "equippedWith" instead?

**Comment by JoachimBenner** [comment]
I can imagine that for some (perpaps rage) applications the information, to which building object a specific energy conversion system belong, sis needed. The more general question is: Is it really necessary to explicitly represent this informtion in  the exchange format? This problem occurs several times in the ADE (e.g. _BoundarySurface <---> _SolarEnergySystem, EnergyConversionSystem <---> EnergyDemand, ThermalZone <---> UsageZone), and sometimes we have modelles bilateral relations, and sometimes unilateral. In principle, an unilateral relation is enough, any software can easily reconstruct the backward relation if this information is needed. On the other hand, the relation from EnergyConversionSystem to _AbstractBuilding is **optional**, so it does not really matter whether we have it or not, no one needs to instanciate it. The most important information is the **cardinality (0..1)**,  which means that an EnergyConversionSystem object belongs to exactly one building.

The relation name "has" surely is quite general, but it is also used for the relations from UsageZone / BuildingUnit to Facilities. If we start to rename relations, we should stay consistant and rename all instances of "has".

My conclusion:
- Leave the optional relation EnergyConversionSystem --> _AbstractBuilding
- Relame the relations _AbstractBuilding --> EnergyConversionSystem, UsageTone --> Facilities and BuildingUnit --> Facilities from "has" to "equippedWith"

**Comment by RomainNouvel** [comment]
Agree.

**Comment by gioagu** [comment]
Agree

**Comment by mlauster** [comment]
@RomainNouvel, is there an agreement on this? If so, does core team takes care of implementation?

**Comment by JoachimBenner** [comment]
From my side, this is o.k.

**Comment by mlauster** [comment]
Proposal:
Relame the relations _AbstractBuilding --> EnergyConversionSystem, UsageTone --> Facilities and BuildingUnit --> Facilities from "has" to "equippedWith"

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model (relations are now named `equippedWith` and `installedIn`)
