### ISSUE TITLE
Rename relations *usageZones* and *thermalZones*

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#94]
In the CityGML standard as well as in the EnergyADE, most relation names are stated in singular. This has a good reason, because in the XML encoding the relation property either points to (via xlink:href) or imbeds exactly one related XML-element. Thus, the new relation *thermalZones* (_AbstractBuilding --> ThermalZone) must be instanciated once for every ThermalZone of the building, and the plural usage in the relation name is misleading and inconsistant with the rest of the data model. The same situation occurs with the relation *usageZones*  (_AbstractBuilding --> UsageZone).

**Proposal:**

1. Rename *thermalZones* --> *thermalZone*
2. Rename *usageZones* --> *usageZone*

**Comment by RomainNouvel** [comment]
Hi Joachim,
Then, the relationship holds the name of the object (without upper case).
is that the standard way to proceed in XML Schema? If so, why is not not done for all relationships?

**Comment by JoachimBenner** [comment]
No, sometimes the XML-element names (with lower case starting character) are used as property names, but not always. My point is simply that it is confusing to write "thermalZone**s**", followed by only one ThermalZone object.

**Comment by gioagu** [comment]
Agree with renaming.

**Comment by bahujean** [comment]
I agree with renaming (without "s" nor any upper case).

  1-  Rename thermalZones --> thermalZone
  2-  Rename usageZones --> usageZone

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
