### ISSUE TITLE
Mandatory and additional  properties for _TimeSeries

### ISSUE THREAD

**Issue by JoachimBenner** [cstb/citygml-energy#95]
For the processing of time series (*_TimeSeries*), it is essential to know how the different values need to be interpreted, e.g. whether they represent the total amount of a measure value or a single value, whether the measure values are related with the preceeding or the succeding time interval, and whether it is feasible to interpolate between different values. This indispensible information can be stated with the property *interpolationType* of *TimeValuesProperties*, with actually is optional but should be mandatory.

In several use cases, the time series will be generated by "meters" (e.g. electricity or gas meters), and the values of the time series represent a "total amount" (InterpolationType *InstantaneousTotal*, *PreceedingTotal* or *SucceedingTotal*). The meters normally have a value different from zero at the starting time of the time series, and this starting value must be known to  interpret the time series values.

**Proposal**

1. Make property *variableProperties* of *_TimeSeries* **mandatory**
2. Make property *interpolationType" of *TimeValuesProperties* **mandatory**
3. **Add optional property** *startValue* (type *Measure*) to *TimeValuesProperties*

**Comment by RomainNouvel** [comment]
Ok for 1. and 2.
For the 3., I can't find an example where it will be useful. This startValue will be either the first value of the TimeSeries, or will remain unknown (if interpolationType = SucceedingTotal).

**Comment by JoachimBenner** [comment]
I agree, in most cases of meter values, the first value of the time series will be the starting value

**Comment by gioagu** [comment]
Agree for 1. and 2. too.
For 3., I guess the point is already clear (no need).

**Comment by JoachimBenner** [comment]
Is agreed. Should be explained in the guidelines

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
