### ISSUE TITLE
LevelOfRefurbishment -> codeList

### ISSUE THREAD

**Issue by RomainNouvel** [cstb/citygml-energy#98]
I think we agreed last meeting in Munich to set the LevelOfRefurbishment as a codeList (extendable) rather than a enumeration, so that anybody may extend this list, depending on the case study and its building libraries.

Do you confirm?

**Comment by gioagu** [comment]
Agree

**Comment by JoachimBenner** [comment]
Agree

**Comment by JoachimBenner** [comment]
Delete attribute in EnergyConversionSystem and _Opening.
Change Enumeration into CodeList

**Comment by JoachimBenner** [comment]
The issue od deleting refurbishment measure attributes in _Opening and EnergyConversionSystem is topic of #42. Does the Energy systems WG accept the proposal?

**Comment by mlauster** [comment]
Fine for us.

**Comment by oliviertournaire** [comment]
Implemented in latest version of the UML model
